sudo: false

env:
  global:
    - RUNTESTFLAGS=-v

addons:
  postgresql: "9.4"

addons:
  apt:
    packages:
    - build-essential
    - autoconf
    - libtool
    - libcunit1-dev
    - xsltproc
    - docbook-xsl
    - docbook-mathml
    - dblatex
    - libproj-dev
    - libgdal-dev
    - libgeos-dev
    - libjson0-dev
    sources:
    - postgresql-9.4
    - postgresql-server-dev-9.4

language: c

compiler: gcc

script:
  - cd postgresql-9.4* && ./configure --prefix=$PWD/../regress/00-regress-install/ && make && make install && cd -
  - PATH=regress/00-regress-install/bin:$PATH
  - ./autogen.sh
  - ./configure --prefix=00-regress-install
  - make
  - make check
  - make install
  - make installcheck

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#postgis"
    on_success: change
    on_failure: always
    use_notice: false
